# common
common_countries = [
    ["fr","CM"],
    ["en","TZ"],
    ["sw","TZ"],
    ["en","ZM"],
    ["en","ZA"],
    ["fr","CD"],
    ["en","UG"],
    ["fr","BF"],
    ["fr","BJ"],
    ["ar","LY"],
    ["ar","TN"],
    ["fr","ML"],
    ["en","LR"],
    ["en","SL"],
    ["en","MW"],
    ["ar","AE"],
    ["fr","RW"],
    ["en","GM"],
    ["en","SS"],
    ["fr","GA"],
    ["ar","SD"],
    ["ar","SO"],
    ["ar","MR"],
    ["ar","DJ"],
]

# normal
normal_countries = [
    ["en","NG"],
    ["en","KE"],
    ["sw","KE"],
    ["en","GH"],
    ["ar","EG"],
    ["ar","SA"],
    ["fr","CI"],
    ["fr","CM"],
    ["ar","DZ"],
    ["en","TZ"],
    ["sw","TZ"],
    ["fr","SN"],
    ["en","ZM"],
    ["ar","MA"],
    ["fr","MA"],
    ["en","ZA"],
    ["fr","CD"],
    ["en","UG"],
    ["fr","BF"],
    ["fr","BJ"],
    ["en","ZW"],
    ["en","ET"],
    ["ar","LY"],
    ["ar","TN"],
    ["fr","ML"],
    ["en","LR"],
    ["en","SL"],
    ["en","MW"],
    ["ar","AE"],
    ["fr","RW"],
    ["en","GM"],
    ["en","SS"],
    ["fr","GA"],
    ["ar","SD"],
    ["ar","SO"],
    ["ar","MR"],
    ["ar","DJ"],
]

countries = common_countries
