# Generated by Django 2.1.5 on 2019-10-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_testreport_monkey_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='automated_testing_report',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='monkey_report',
            field=models.FileField(default=None, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='performance_report',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
